// generated by "sampctl package generate"

#include "sampgo.inc"

#define DEFAULT_EVENT ("default_event")

main() {
	// write tests for libraries here and run "sampctl package run"
	static
		retval = sampgo_CallEvent(DEFAULT_EVENT);

	printf("event called: %s\nretval: %d", DEFAULT_EVENT, retval);
}
